// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/appointments" | "/admin/appointments/[id]" | "/admin/customers" | "/admin/customers/[id]" | "/admin/customers/[id]/edit" | "/admin/customers/new" | "/admin/login" | "/admin/orders" | "/admin/orders/[id]" | "/admin/orders/[id]/document" | "/admin/orders/new" | "/admin/reports" | "/admin/services" | "/admin/services/[id]" | "/admin/services/[id]/edit" | "/admin/services/new" | "/admin/users" | "/admin/users/[id]/edit" | "/admin/users/new" | "/cart" | "/checkout" | "/documents/order/[id]" | "/services" | "/services/[slug]" | "/track"
type AppRouteHandlerRoutes = "/admin/orders/[id]/document/download" | "/admin/orders/[id]/files/download" | "/api/cron/appointment-reminders"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/appointments": {}
  "/admin/appointments/[id]": { "id": string; }
  "/admin/customers": {}
  "/admin/customers/[id]": { "id": string; }
  "/admin/customers/[id]/edit": { "id": string; }
  "/admin/customers/new": {}
  "/admin/login": {}
  "/admin/orders": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/orders/[id]/document": { "id": string; }
  "/admin/orders/[id]/document/download": { "id": string; }
  "/admin/orders/[id]/files/download": { "id": string; }
  "/admin/orders/new": {}
  "/admin/reports": {}
  "/admin/services": {}
  "/admin/services/[id]": { "id": string; }
  "/admin/services/[id]/edit": { "id": string; }
  "/admin/services/new": {}
  "/admin/users": {}
  "/admin/users/[id]/edit": { "id": string; }
  "/admin/users/new": {}
  "/api/cron/appointment-reminders": {}
  "/cart": {}
  "/checkout": {}
  "/documents/order/[id]": { "id": string; }
  "/services": {}
  "/services/[slug]": { "slug": string; }
  "/track": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
